name: pythia160m
seed_num: null
output_directory: trained_models
model_config_path: EleutherAI/pythia-160m
tokenizer_path: EleutherAI/pythia-160m
train_type: hf
validation_type: local
hf_train: HuggingFaceFW/fineweb-edu
hf_train_config: CC-MAIN-2013-20
hf_train_split: train
local_train_path: null
local_train_files: null
hf_validation: null
hf_validation_config: null
hf_validation_split: null
local_validation_path: test_sets
local_validation_files: validation_set.parquet
model_save_step: 10
maximum_save_steps: 1000
max_context_length: 1024
batch_size: 64
gradient_accumulation: 8
lr_scheduler: cosine